# docker-compose -f superadmin.yml up sphinx-swarm-superadmin -d

version: "2"

services:
  load_balancer:
    image: traefik:v2.9
    container_name: load_balancer
    restart: unless-stopped
    networks:
      - sphinx-swarm
    command:
      - "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--entrypoints.web.http.redirections.entrypoint.to=websecure"
      - "--entrypoints.web.http.redirections.entrypoint.scheme=https"
      - "--certificatesresolvers.myresolver.acme.tlschallenge=true"
      - "--certificatesresolvers.myresolver.acme.email=evanfeenstra@gmail.com"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
      # - "--certificatesresolvers.myresolver.acme.dnschallenge=true"
      # - "--certificatesresolvers.myresolver.acme.dnschallenge.provider=route53"
      # - "--certificatesresolvers.myresolver.acme.caserver=https://acme-v02.api.letsencrypt.org/directory"
    ports:
      # The HTTP port
      - 80:80
      # The Web UI (enabled by --api.insecure=true)
      - 8080:8080
      # entrypoints
      - 443:443
    volumes:
      # So that Traefik can listen to the Docker events
      - /var/run/docker.sock:/var/run/docker.sock
      - /home/admin/letsencrypt:/letsencrypt
    environment:
      - AWS_REGION=$AWS_REGION
    logging:
      options:
        max-size: 10m

  sphinx-swarm-superadmin:
    image: sphinxlightning/sphinx-swarm-superadmin:setup-ready-to-go-swarm
    container_name: sphinx-swarm-superadmin
    networks:
      - sphinx-swarm
    depends_on:
      - load_balancer
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /home/admin/vol:/vol
    ports:
      - 8000:8000
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.elements.rule=Host(`app.${HOST}`)"
      - "traefik.http.services.elements.loadbalancer.server.port=8000"
      - "traefik.http.routers.elements.tls=true"
      - "traefik.http.routers.elements.tls.certresolver=myresolver"
      - "traefik.http.routers.elements.entrypoints=websecure"
    restart: unless-stopped
    environment:
      - DOCKER_RUN=true 
      - ROCKET_ADDRESS=0.0.0.0
      - ROCKET_PORT=8000
      - SUPER_TOKEN=$SUPER_TOKEN
      - SECOND_BRAIN_ONLY=$SECOND_BRAIN_ONLY
      - AWS_REGION=$AWS_REGION
      - SUPER_URL=$SUPER_URL
      - STAKWORK_ADD_NODE_TOKEN=$STAKWORK_ADD_NODE_TOKEN
      - STAKWORK_RADAR_REQUEST_TOKEN=$STAKWORK_RADAR_REQUEST_TOKEN
      - YOUTUBE_API_TOKEN=$YOUTUBE_API_TOKEN
      - TWITTER_BEARER=$TWITTER_BEARER
      - EXTERNAL_LND_MACAROON=$EXTERNAL_LND_MACAROON
      - EXTERNAL_LND_ADDRESS=$EXTERNAL_LND_ADDRESS
      - EXTERNAL_LND_CERT=$EXTERNAL_LND_CERT
      - JARVIS_FEATURE_FLAG_SCHEMA=$JARVIS_FEATURE_FLAG_SCHEMA
      - FEATURE_FLAG_ADD_NODE_KEY=$FEATURE_FLAG_ADD_NODE_KEY
      - BACKUP=$BACKUP
      - FEATURE_FLAG_TEXT_EMBEDDINGS=$FEATURE_FLAG_TEXT_EMBEDDINGS
      - ROUTE53_ZONE_ID=$ROUTE53_ZONE_ID
      - AWS_DEVICE_NAME=$AWS_DEVICE_NAME
      - AWS_IMAGE_ID=$AWS_IMAGE_ID
      - AWS_SECURITY_GROUP_ID=$AWS_SECURITY_GROUP_ID
      - AWS_KEY_NAME=$AWS_KEY_NAME
      - AWS_SUBNET_ID=$AWS_SUBNET_ID
      - SWARM_TAG_VALUE=$SWARM_TAG_VALUE
      - SWARM_TAG_KEY=$SWARM_TAG_KEY
      - SWARM_UPDATER_PASSWORD=$SWARM_UPDATER_PASSWORD
      - EC2_DAILY_LIMIT=$EC2_DAILY_LIMIT
      - QUESTION_AND_ANSWER_WORKFLOW_ID=$QUESTION_AND_ANSWER_WORKFLOW_ID
      - AWS_S3_BUCKET_NAME=$AWS_S3_BUCKET_NAME
      - AWS_USER_ROLE=$AWS_USER_ROLE
      - GITHUB_REQUEST_TOKEN=$GITHUB_REQUEST_TOKEN
      - SINGLE_AUDIO_OR_VIDEO_EPISODE_WORKFLOW_ID=$SINGLE_AUDIO_OR_VIDEO_EPISODE_WORKFLOW_ID
      - GITHUB_PAT=$GITHUB_PAT
      - LOG_TAIL_LENGTH=$LOG_TAIL_LENGTH
      - RESERVE_SWARM_ENABLED=$RESERVE_SWARM_ENABLED
      - MINIMUM_RESERVED_INSTANCES=$MINIMUM_RESERVED_INSTANCES
      - SWARM_RESERVER_CRON_TIME=$SWARM_RESERVER_CRON_TIME
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    networks:
      - sphinx-swarm
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - 9090:9090
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.prometheus.rule=Host(`prometheus.${HOST}`)"
      - "traefik.http.services.prometheus.loadbalancer.server.port=9090"
      - "traefik.http.routers.prometheus.tls=true"
      - "traefik.http.routers.prometheus.tls.certresolver=myresolver"
      - "traefik.http.routers.prometheus.entrypoints=websecure"
    volumes:
      - ./prometheus:/etc/prometheus
      - prom_data:/prometheus
  grafana:
    image: grafana/grafana
    container_name: grafana
    networks:
      - sphinx-swarm
    ports:
      - 3000:3000
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.grafana.rule=Host(`grafana.${HOST}`)"
      - "traefik.http.services.grafana.loadbalancer.server.port=3000"
      - "traefik.http.routers.grafana.tls=true"
      - "traefik.http.routers.grafana.tls.certresolver=myresolver"
      - "traefik.http.routers.grafana.entrypoints=websecure"
    environment:
      - GF_SECURITY_ADMIN_USER=$GF_SECURITY_ADMIN_USER
      - GF_SECURITY_ADMIN_PASSWORD=$GF_SECURITY_ADMIN_PASSWORD
    volumes:
      - ./grafana:/etc/grafana/provisioning/datasources
    
networks:
  sphinx-swarm:
    external: true

volumes:
  prom_data:
